### ISSUE TITLE
[React-Quill editor] bold, italic 체 적용 안됨 이슈

### ISSUE THREAD

**Issue by Haze-S** [Rolling-8/Rolling#41]
## 어떤 버그인가요?

에디터 안에서 bold, italic 글씨체가 적용이 안됩니다.

## 어떤 상황에서 발생한 버그인가요?

메세지 등록 시 에디터에서 글씨체 적용이 안됨

## 예상 결과

글씨체가 아이콘 선택에 따라 올바로 적용되어야 함

**Comment by JooKangsan** [comment]
이건 제가 가져갈게요!
